FROM tomcat:8.5-jre8

COPY tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

#docker run -d --name=tomcat --net=prod-network --ip=172.18.0.3 -p 8281:8080 -v prod:/usr/local/tomcat/webapps tomcat